# Generated by Django 4.2.1 on 2023-06-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.FloatField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('pr_nombre', models.CharField(max_length=30)),
                ('seg_nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('fec_nac', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('pr_nombre', models.CharField(max_length=30)),
                ('seg_nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('fec_nac', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('total_productos', models.IntegerField()),
                ('total_pago', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'item_carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_libro', models.CharField(blank=True, max_length=30, null=True)),
                ('autor', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_mantencion', models.DateField()),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fec_transaccion', models.DateField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('pr_nombre', models.CharField(max_length=30)),
                ('seg_nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('fec_nac', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tecnico',
                'managed': False,
            },
        ),
    ]
